export type LocationErrorCode =
  | 'PERMISSION_DENIED'
  | 'PERMISSION_DENIED_IOS'
  | 'PERMISSION_DENIED_ANDROID'
  | 'ADDRESS_FETCH_ERROR'
  | 'ADDRESS_NOT_FOUND'
  | 'POSITION_UNAVAILABLE'
  | 'TIMEOUT'
  | 'BROWSER_NOT_SUPPORTED';
